version: '3.8'

services:
  ncrelay:
    build: .
    image: ncrelay:latest
    container_name: ncrelay
    restart: unless-stopped
    ports:
      - "${PORT:-9004}:${PORT:-9004}"
    volumes:
      - ncrelay-data:/data:rw
      - ncrelay-logs:/data/logs:rw
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${PORT:-9004}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - ncrelay-network

networks:
  ncrelay-network:
    driver: bridge

volumes:
  ncrelay-data:
  ncrelay-logs:
